# -*- coding: utf-8 -*-
"""tarea_02 Cisterna

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SfZl4fMBBQfR_uZZfFBOC3ZPQOdBFGmL

Hacer un programa que imprima los números del 1 al 100.
"""

lista_de_numeros = list(range(1,101))
print(lista_de_numeros)

"""Hacer un programa que imprima los números del 1 al 100 que sean divisibles entre 3 (con resto 0)

Esto signifca que si el número es 3, 6, 9, 12, 15, etc. entonces debe imprimirlo ya que la división de esos números por 3 da como resto 0, exacto.
"""

lista_de_numeros = list(range(1,101))
for numero in lista_de_numeros:
 if numero % 3 == 0:
  print (numero)

"""Pseudocódigo, Sumador y comparador de dos números Realiza el algoritmo para un sumador de dos números. Si el resultado es menor a 100 se mostrará el mensaje "menor a 100", si el resultado es mayor a 100, pero menor a 150 mostrará el mensaje "mayor a 100", pero si es mayor a 150 mostrará el mensaje "mayor a 150"
"""

a = input("ingrese un numero")
a = int(a)
b = 35
suma_de_dos_numeros = a + b
if suma_de_dos_numeros < 100:
  print("menor a 100")
elif 150 > suma_de_dos_numeros > 100:
  print ("es mayor a 100 y menor a 150")
elif suma_de_dos_numeros > 150:
  print("mayor a 150")

"""Generar un programa que combine variables, tipos de datos y una condicional en Python (hacer una función que evalúe si el usuario es mayor de edad y si le gusta la programación, que envíe diferentes textos según la respuesta del usuario)

"""

def evaluar_usuario(ser_feliz, jugar_ajedrez):
  if (ser_feliz and jugar_ajedrez) == True:
    print("imposible")
  else:
   print("eres normal")

